'use strict';
const {hash,read,fail,percent,EVENTS}=require('../lib/content-effect-contract');const {createEffectStore}=require('../lib/content-effect-store');
const missing=e=>/exist|ResourceNotFound/i.test(String(e.code)+e.message);
function createContentEffectReport({db,enabled=process.env.CONTENT_EFFECTS_ENABLED==='true',now=Date.now}){
 async function rows(c,where,limit=101){try{return (await db.collection(c).where(where).limit(limit).get()).data||[];}catch(e){if(missing(e))return [];throw e;}}
 function days(e){const today=new Date(now()+8*3600000).toISOString().slice(0,10),from=e.from||today,to=e.to||from;const valid=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;if(!valid(from)||!valid(to)||from>to||(Date.parse(to)-Date.parse(from))/86400000>6)fail('EFFECT_DATES','请选择最多连续7天的日期范围');return Array.from({length:(Date.parse(to)-Date.parse(from))/86400000+1},(_,i)=>new Date(Date.parse(from)+i*86400000).toISOString().slice(0,10));}
 async function list(e){const dates=days(e);if(e.kind&&!EVENTS[e.kind])fail('EFFECT_KIND','内容类型错误');await createEffectStore({db,enabled}).cleanup();const groups=new Map();let partial=false;for(const day of dates){const found=await rows('content_effect_daily',{day,...(e.kind?{kind:e.kind}:{})});if(found.length>100)partial=true;for(const r of found.slice(0,100)){const key=hash([r.kind,r.contentId,r.version].join('|'));let g=groups.get(key);if(!g){g={key,kind:r.kind,contentId:r.contentId,version:r.version,title:r.title,model:r.model||'',promptVersion:r.promptVersion||'',codeVersion:r.codeVersion||'',counts:{}};groups.set(key,g);}for(const [event,n] of Object.entries(r.counts||{})){if(event==='open'||event==='submitted'||EVENTS[r.kind]?.includes(event)||/^(exit|timeout)_/.test(event))g.counts[event]=(g.counts[event]||0)+Math.max(0,Number(n)||0);}}}
 const items=[...groups.values()].map(g=>({...g,rates:Object.fromEntries(['source_open','explore','read_mark','contribute_start','submitted','complete'].map(k=>[k,partial?null:percent(g.counts[k]||0,g.counts.open||0)]))}));return {ok:true,enabled,items,partial,from:dates[0],to:dates.at(-1),notes:['计数为内容浏览批次，不是人数；同一次浏览的同类操作最多计一次。','没有读完或收听完的推断；关闭上报可能丢失，超时不等于真实退出。','比例仅在打开至少20次、分子与剩余均至少5次时显示；不能据此证明因果或事实正确。',partial?'数据超过本页范围，比例已隐藏，请缩小日期或内容类型。':'单日最多100条汇总；不同版本需在同一筛选范围下比较。']};}
 async function detail(e){const dates=days(e);if(!EVENTS[e.kind]||typeof e.contentId!=='string'||e.contentId.length>128||typeof e.version!=='string'||e.version.length>160)fail('EFFECT_INPUT','内容参数不合法');let starts=0,submitted=0,partial=false;const submissions=new Map(),supplements=new Map();for(const day of dates){const aggregateId=hash(JSON.stringify([day,e.kind,e.contentId,e.version]));const aggregate=await read(db,'content_effect_daily',aggregateId);if(!aggregate)continue;starts+=aggregate.counts.contribute_start||0;submitted+=aggregate.counts.submitted||0;for(const [collection,target] of [['submissions',submissions],['submission_supplements',supplements]]){const found=await rows(collection,{effectAggregateId:aggregateId});partial ||=found.length>100;for(const r of found.slice(0,100))target.set(r._id,r);}}
 let approved=0,adopted=0;for(const s of submissions.values()){if(s.status!=='approved'||s.withdrawnAt||s.disabledAt||s.sourceUnavailable)continue;approved++;const c=await rows('story_contributions',{submissionId:s._id});partial ||=c.length>100;if(c.some(x=>x.status==='adopted'))adopted++;}for(const s of supplements.values())if(s.status==='approved')approved++;
 partial ||= submitted!==submissions.size+supplements.size;
 let quality={available:false,note:'审核质量仍在原工作台查看，不能用使用量代替。'};
 if(e.kind==='guide'){const records=await rows('guide_fragment_logs',{fragmentId:e.contentId,action:'generation_review'});const ratings={correct:0,partial:0,incorrect:0};let reviewed=0,modified=0;for(const r of records){if(e.version!==e.contentId+'_v'+r.revision)continue;reviewed++;if(ratings[r.humanRating]!==undefined)ratings[r.humanRating]++;if(JSON.stringify(r.original?.sentences)!==JSON.stringify(r.final?.sentences))modified++;}quality={available:true,reviewed,modified,ratings,partial:records.length>100,note:'管理员对这个发布版本的判断；与游客使用效果分开。'};}
 const notes=await rows('content_effect_feedback',{kind:e.kind,contentId:e.contentId,version:e.version},1);const note=notes[0];
 return {ok:true,feedback:note?{note:note.note,status:note.status,revision:note.revision}:{note:'',status:'pending',revision:0},flow:{entered:starts,submitted,approved,adopted,partial,submissionRate:partial?null:percent(submitted,starts),approvalRate:partial?null:percent(approved,submitted),adoptionRate:partial?null:percent(adopted,submitted),note:'最后一次明确进入补充归因；通过数按当前审核状态，采用数按当前正式采用记录（不代表仍公开）。附件通过不推断为正式采用。缺失或超限时不计算比例。'},quality};
 }
 async function feedback(e,reviewer){if(!EVENTS[e.kind]||typeof e.contentId!=='string'||e.contentId.length>128||typeof e.version!=='string'||e.version.length>160||!['pending','resolved'].includes(e.status)||typeof e.note!=='string'||e.note.trim().length<4||e.note.length>400)fail('EFFECT_FEEDBACK','请填写4至400字的优化说明，并选择处理状态');for(const c of ['content_effect_feedback','moderation_logs'])await db.createCollection(c).catch(err=>{if(!missing(err))throw err;});const key=hash([e.kind,e.contentId,e.version].join('|'));await db.runTransaction(async tx=>{const old=await read(tx,'content_effect_feedback',key);if((old?.revision||0)!==Number(e.revision||0))fail('EFFECT_CONFLICT','另一管理员已修改，请重新读取');const record={kind:e.kind,contentId:e.contentId,version:e.version,note:e.note.trim(),status:e.status,revision:(old?.revision||0)+1};await tx.collection('content_effect_feedback').doc(key).set(record);await tx.collection('moderation_logs').add({action:'content_effect_feedback',contentKey:key,revision:record.revision,status:record.status,reviewerId:reviewer,createdAt:db.serverDate()});});return {ok:true};}
 return {list,detail,feedback};
}
module.exports={createContentEffectReport};
