'use strict';
const {read,fail}=require('../lib/content-effect-contract');const {checkGuideEvidence}=require('../lib/guide-evidence');const {materialLinkValid}=require('../lib/material-evidence');const {loadPublicTheme}=require('./story-themes');const {createEffectStore}=require('../lib/content-effect-store');
const bursts=new Map();
function createContentEffects({db,enabled=process.env.CONTENT_EFFECTS_ENABLED==='true'}){
 async function resolve(t){if(!t||!['story','theme','guide','route'].includes(t.kind))fail('EFFECT_INPUT','内容类型无效');
 if(t.kind==='route'){if(!['walk','transit','car'].includes(t.mode)||![60,120,240,720].includes(t.minutes)||!['1','2-4','5-8'].includes(t.stops))fail('EFFECT_INPUT','路线仅接受粗粒度方案');const id=[t.mode,t.minutes,t.stops].join('_');return {kind:'route',id,version:'route-plan-v1',title:({walk:'步行',transit:'公交',car:'驾车'}[t.mode])+' / '+t.minutes+'分钟档 / '+t.stops+'站档'};}
 if(typeof t.id!=='string'||!/^[\w-]{1,128}$/.test(t.id))fail('EFFECT_INPUT','内容编号无效');
 if(t.kind==='theme'){const theme=await loadPublicTheme(db,t.id);return theme&&String(theme.version)===String(t.version)?{kind:t.kind,id:t.id,version:String(theme.version),title:theme.title}:null;}
 if(t.kind==='guide'){const f=await read(db,'guide_fragment_versions',t.id),root=f&&await read(db,'guide_fragments',f.id);if(!f||f.status!=='published'||f.simulated||root?.status==='archived'||root?.publishedVersionId!==t.id)return null;await checkGuideEvidence(db,f);return {kind:t.kind,id:f.id,version:t.id,title:f.title,model:f.generation?.model,promptVersion:f.generation?.promptVersion,codeVersion:f.generation?.codeVersion};}
 const s=await read(db,'story_chains',t.id);if(!s||s.status!=='published'||s.needsSourceReview||String(s.version||1)!==String(t.version))return null;const resource=await read(db,'resources',s.resourceId);if(resource?.status!=='published')return null;const ids=[...new Set([...(s.sourceLinkIds||[]),...(s.chapters||[]).flatMap(c=>c.sourceLinkIds||[])])];if(!ids.length)return null;for(const id of ids){const link=await read(db,'story_evidence_links',id),origin=link&&await read(db,'submissions',link.submissionId);if(!link||link.status!=='confirmed'||link.needsSourceReview||link.resourceId!==s.resourceId||!origin||origin.status!=='approved'||origin.aiConsentRevokedAt||origin.aiAnalysisStatus==='consent_revoked'||origin.withdrawnAt||origin.disabledAt||origin.sourceUnavailable||!await materialLinkValid(db,link,origin,true))return null;}return {kind:t.kind,id:t.id,version:String(s.version||1),title:s.title||resource.title};
 }
 const store=createEffectStore({db,resolve,enabled});return {...store,resolve,async handle(e,caller=''){if(enabled&&e.action==='beginContentEffect'&&caller){const now=Date.now();for(const [k,v] of bursts)if(v.until<now)bursts.delete(k);const key=require('../lib/content-effect-contract').hash(caller);const b=bursts.get(key)||{until:now+60000,count:0};if(b.count>=30||bursts.size>1000)return {ok:true,enabled:false};b.count++;bursts.set(key,b);}return e.action==='beginContentEffect'?store.begin(e):store.event(e);}};
}
module.exports={createContentEffects};
