'use strict';
const {read}=require('../lib/guide-evidence');const E=require('../lib/visit-engine');const {createCulturalGuideService}=require('./cultural-guide');const {loadPublicTheme}=require('./story-themes');
const fail=message=>{throw Object.assign(new Error(message),{code:'VISIT_RECORD_INVALID'});};
async function resolve(db,entry,session){if(!['story','source','theme'].includes(entry.kind))return null;
 if(entry.kind==='theme'){const t=await loadPublicTheme(db,E.id(entry.targetId));return t&&t.nodes.some(n=>session.stops.some(s=>s.resourceId===n.resourceId))?{version:String(t.version),title:t.title,url:'./themes.html?id='+encodeURIComponent(t.id)}:null;}
 if(!session.stops.some(s=>s.resourceId===entry.resourceId))return null;const r=await createCulturalGuideService({db}).station({resourceId:entry.resourceId});for(const f of r.items){if(entry.kind==='story'&&f.storyId===entry.targetId)return {version:String(f.storyVersion),title:f.title,url:'./index.html?storyResourceId='+encodeURIComponent(entry.resourceId)};const source=f.sources.find(s=>s.id===entry.targetId);if(entry.kind==='source'&&source)return {version:String(f.versionId),title:source.title,url:'./guide.html',excerpt:source.excerpt};}return null;}
function createVisitRecordService({db}){async function owned(uid,id,tx=db){const s=await read(tx,'visit_sessions',E.id(id));if(!s||s.userId!==uid)fail('找不到你的游览记录');return s;}
 async function context(uid,e){const resource=await read(db,'resources',E.id(e.resourceId));if(!resource||resource.status!=='published')fail('这个站点已不可用');let sessionId='';if(e.sessionId){const s=await owned(uid,e.sessionId);if(!s.stops.some(x=>x.resourceId===e.resourceId))fail('该站点不属于本次行程');sessionId=s.id;}return {ok:true,sessionId,resourceId:e.resourceId,title:String(resource.title||'').slice(0,120),location:resource.location?E.point(resource.location):null};}
 async function activity(uid,e){const s=await owned(uid,e.sessionId);const entry={kind:String(e.kind||''),targetId:E.id(e.targetId),resourceId:e.resourceId?E.id(e.resourceId):'',type:e.type==='read'?'read':e.type==='bookmark'?'bookmark':e.type==='unbookmark'?'unbookmark':''};if(!entry.type)fail('记录类型无效');if(entry.type!=='unbookmark'){const current=await resolve(db,entry,s);if(!current)fail('内容已下架或来源待复核');entry.version=current.version;}return db.runTransaction(async tx=>{const current=await owned(uid,e.sessionId,tx);if(current.revision!==Number(e.revision))fail('行程已更新，请先重新读取');const key=x=>[x.kind,x.targetId,x.type].join(':');let activities=(current.activities||[]).filter(x=>key(x)!==key(entry)&&!(entry.type==='unbookmark'&&x.type==='bookmark'&&x.kind===entry.kind&&x.targetId===entry.targetId));if(entry.type!=='unbookmark')activities.push({...entry,at:new Date().toISOString()});activities=activities.slice(-200);const revision=current.revision+1;await tx.collection('visit_sessions').doc(current.id).update({activities,revision});return {ok:true,activities,revision};});}
 async function summary(uid,e){const s=await owned(uid,e.sessionId),items=[];for(const entry of s.activities||[]){const value=await resolve(db,entry,s);items.push({...entry,available:!!value,...(value||{title:'内容已下架或来源待复核'}),recordedVersion:entry.version||'',updated:!!value&&!!entry.version&&entry.version!==value.version});}const rows=(await db.collection('submissions').where({userId:uid}).limit(100).get()).data||[];return {ok:true,items,submissions:rows.filter(r=>r.visitSessionId===s.id).map(r=>({id:r._id||r.id,title:r.title,status:r.status,resourceId:r.visitResourceId})),submissionLimit:100};}
 return {context,activity,summary};}
module.exports={createVisitRecordService,resolve};
